char *ww_en[] = {"Hey NXP", "Hey NXP", "Hey NXP", "Hey NXP", "Hey NXP"};

char *cmd_iot_en[] = {"Temperature Up", "Temperature Up", "Temperature Down", "Temperature Down", "Window Up",
                      "Window Down",    "Turn On",        "Turn On",          "Turn Off",         "Brighter",
                      "Darker"};

char *cmd_elevator_en[] = {"Floor One",  "Floor One",  "Floor Two",  "Floor Three", "Floor Four",
                           "Floor Five", "Main Lobby", "Going Up",   "Going Up",    "Going Down",
                           "Going Down", "Open Door",  "Close Door", "Close Door"};

char *cmd_audio_en[] = {"Turn On", "Turn On",    "Turn Off",   "Play",           "Pause",     "Start",
                        "Stop",    "Next Track", "Next Track", "Previous Track", "Volume Up", "Volume Down"};

char *cmd_wash_en[] = {"Wash Delicate", "Wash Normal", "Wash Heavy Duty", "Wash Heavy Duty",
                       "Wash Whites",   "Wash Whites", "Cancel"};

char *cmd_led_en[] = {"L, E, D, Red", "L, E, D, Green", "L, E, D, Blue", "Cycle Fast", "Cycle Slow"};

char *cmd_dialogic_1_en[] = {"Set Preheat", "Set Pre Heat", "Set Bake", "Set Broil", "Set Timer"};

char *cmd_dialogic_2_temperature_en[] = {
    "two hundred degrees",           "two hundred degrees",           "two hundred degrees",
    "two hundred ten degrees",       "two hundred ten degrees",       "two hundred ten degrees",
    "two hundred twenty degrees",    "two hundred twenty degrees",    "two hundred twenty degrees",
    "two hundred twenty degrees",    "two hundred twenty degrees",    "two hundred twenty degrees",
    "two hundred thirty degrees",    "two hundred thirty degrees",    "two hundred thirty degrees",
    "two hundred thirty degrees",    "two hundred thirty degrees",    "two hundred thirty degrees",
    "two hundred forty degrees",     "two hundred forty degrees",     "two hundred forty degrees",
    "two hundred fifty degrees",     "two hundred fifty degrees",     "two hundred fifty degrees",
    "two hundred sixty degrees",     "two hundred sixty degrees",     "two hundred sixty degrees",
    "two hundred seventy degrees",   "two hundred seventy degrees",   "two hundred seventy degrees",
    "two hundred seventy degrees",   "two hundred seventy degrees",   "two hundred seventy degrees",
    "two hundred eighty degrees",    "two hundred eighty degrees",    "two hundred eighty degrees",
    "two hundred ninety degrees",    "two hundred ninety degrees",    "two hundred ninety degrees",
    "three hundred degrees",         "three hundred degrees",         "three hundred degrees",
    "three hundred ten degrees",     "three hundred ten degrees",     "three hundred ten degrees",
    "three hundred twenty degrees",  "three hundred twenty degrees",  "three hundred twenty degrees",
    "three hundred twenty degrees",  "three hundred twenty degrees",  "three hundred twenty degrees",
    "three hundred thirty degrees",  "three hundred thirty degrees",  "three hundred thirty degrees",
    "three hundred thirty degrees",  "three hundred thirty degrees",  "three hundred thirty degrees",
    "three hundred forty degrees",   "three hundred forty degrees",   "three hundred forty degrees",
    "three hundred fifty degrees",   "three hundred fifty degrees",   "three hundred fifty degrees",
    "three hundred sixty degrees",   "three hundred sixty degrees",   "three hundred sixty degrees",
    "three hundred seventy degrees", "three hundred seventy degrees", "three hundred seventy degrees",
    "three hundred seventy degrees", "three hundred seventy degrees", "three hundred seventy degrees",
    "three hundred eighty degrees",  "three hundred eighty degrees",  "three hundred eighty degrees",
    "three hundred ninety degrees",  "three hundred ninety degrees",  "three hundred ninety degrees",
    "four hundred degrees",          "four hundred degrees",          "four hundred degrees",
    "four hundred ten degrees",      "four hundred ten degrees",      "four hundred ten degrees",
    "four hundred twenty degrees",   "four hundred twenty degrees",   "four hundred twenty degrees",
    "four hundred twenty degrees",   "four hundred twenty degrees",   "four hundred twenty degrees",
    "four hundred thirty degrees",   "four hundred thirty degrees",   "four hundred thirty degrees",
    "four hundred thirty degrees",   "four hundred thirty degrees",   "four hundred thirty degrees",
    "four hundred forty degrees",    "four hundred forty degrees",    "four hundred forty degrees",
    "four hundred fifty degrees",    "four hundred fifty degrees",    "four hundred fifty degrees",
    "four hundred sixty degrees",    "four hundred sixty degrees",    "four hundred sixty degrees",
    "four hundred seventy degrees",  "four hundred seventy degrees",  "four hundred seventy degrees",
    "four hundred seventy degrees",  "four hundred seventy degrees",  "four hundred seventy degrees",
    "four hundred eighty degrees",   "four hundred eighty degrees",   "four hundred eighty degrees",
    "four hundred ninety degrees",   "four hundred ninety degrees",   "four hundred ninety degrees",
    "five hundred degrees",          "five hundred degrees",          "five hundred degrees"};

char *cmd_dialogic_2_timer_en[] = {"one minute",
                                   "one minute",
                                   "one minute",
                                   "one minute",
                                   "one minute",
                                   "one minute",
                                   "one minute",
                                   "one minute",
                                   "two minutes",
                                   "three minutes",
                                   "four minutes",
                                   "five minutes",
                                   "six minutes",
                                   "seven minutes",
                                   "eight minutes",
                                   "nine minutes",
                                   "ten minutes",
                                   "fifteen minutes",
                                   "twenty minutes",
                                   "twenty minutes",
                                   "twenty five minutes",
                                   "twenty five minutes",
                                   "twentyFive minutes",
                                   "twentyFive minutes",
                                   "thirty minutes",
                                   "thirty minutes",
                                   "thirty five minutes",
                                   "thirty five minutes",
                                   "thirtyFive minutes",
                                   "thirtyFive minutes",
                                   "forty minutes",
                                   "forty five minutes",
                                   "fortyFive minutes",
                                   "fifty minutes",
                                   "fifty five minutes",
                                   "fiftyFive minutes",
                                   "sixty minutes",
                                   "ninety minutes",
                                   "one hour",
                                   "one hour",
                                   "one hour",
                                   "one hour",
                                   "two hours",
                                   "two hours",
                                   "three hours",
                                   "three hours"};
